<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ios</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*.+$</string>
	<key>foldingStopMarker</key>
	<string>^\s*!.*$</string>
	<key>name</key>
	<string>Cisco IOS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ip_address</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#url</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#router</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface_clause</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>puncuation.definition.comment.ios</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(!).*$\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.ios</string>
				</dict>
			</array>
		</dict>
		<key>control</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ios</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(no|no sh|shut|shutdown|reload|reset|activate)\b</string>
				</dict>
			</array>
		</dict>
		<key>interface_clause</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(interface|int)\s+(?=[A-Za-z-]+[0-9/. ]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.interface.ios</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.interface.ios</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interface_id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.interface-id.ios</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>interface_id</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(?i:(?i:fast|gigabit|)ethernet|null|bvi|virtual-?[a-z]*|fa|gi|e|se|serial|lo|loopback|tun|tunnel)(?=\s?[0-9])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.type.interface.ios</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.interface-id.ios</string>
					<key>end</key>
					<string>([0-9][0-9/. ]*)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.interface-number.ios</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>ip_address</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\s</string>
					<key>name</key>
					<string>constant.numeric.ip-address.ios</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s(?:(?:25[6-9]|2[6-9][0-9]|[3-9]?[0-9][0-9]?)\.)\b</string>
					<key>name</key>
					<string>invalid.illegal.ip-address.ios</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:[1-9]+[0-9]*|0)\b</string>
					<key>name</key>
					<string>constant.numeric.integer.ios</string>
				</dict>
			</array>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:eq|neq|gt|lt|range|ge|le)\b</string>
					<key>name</key>
					<string>keyword.operator.comparison.ios</string>
				</dict>
			</array>
		</dict>
		<key>router</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(router)\s+(?=[A-Za-z-]+[0-9 ]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.router.ios</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.router.ios</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#router_id</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?:.*$)</string>
							<key>name</key>
							<string>invalid.illegal.router-id.ios</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>router_id</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(?i:eigrp|rip|isis|odr|ospf|bgp|mobile)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.type.router.ios</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.router-id.ios</string>
					<key>end</key>
					<string>(?:\s+(?:[0-9]+)|(?:[A-Z]+)|)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.router-number.ios</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.router-tag.ios</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>url</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(https?|t?ftps?|flash|disk[0-9]|scp|ssh|telnet):(?=[A-Za-z0-9_./-])</string>
					<key>end</key>
					<string>(?=\s+)</string>
					<key>name</key>
					<string>string.unquoted.ios</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>User created objects</string>
					<key>match</key>
					<string>\b([A-Z]+[A-Z0-9_ -]*)\b</string>
					<key>name</key>
					<string>variable.parameter.ios</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.ios</string>
	<key>uuid</key>
	<string>3818ca6a-1ea2-497b-ba32-d1cfc42ed4a0</string>
</dict>
</plist>
